// AUTO-GENERATED by `npm run sync` (scripts/sync-resume-data.ts).
// 원본은 ../../../src/constants 입니다. 이 파일을 직접 수정하지 마세요.
export const PROFILE = {
  "name": "김계승",
  "nameEn": "Kim Kyeseung",
  "title": "프론트엔드 개발자",
  "subTitle": "Frontend Developer with Full-Stack Capabilities",
  "yearsOfExperience": 6,
  "email": "kimkyeseung@gmail.com",
  "phone": "010-2848-9508",
  "github": "https://github.com/kimkyeseung",
  "behance": "https://www.behance.net/kimkyeseung",
  "address": "서울 영등포구 당산동",
  "introduction": "6년차 프론트엔드 개발자로 React, Next.js, Vue.js를 활용한 웹 애플리케이션 개발에 전문성을 가지고 있습니다. 디자이너 출신으로 사용자 경험에 대한 깊은 이해를 바탕으로 개발하며, 백엔드 개발 경험을 통해 전체 시스템을 아우르는 시야를 갖추고 있습니다."
} as const
