/**
 * src/constants(홈페이지 이력서 원본)에서 데이터를 읽어 mcp-server/src/data/*.ts를
 * 자동 생성한다. `npm run build`(및 `npm run sync`)가 항상 이 스크립트를 먼저 실행하므로,
 * 홈페이지의 이력서 내용을 수정한 뒤 mcp-server를 다시 빌드하기만 하면 MCP 서버에도
 * 최신 내용이 반영된다. 이 스크립트가 만드는 파일은 손으로 수정하지 않는다.
 */
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import fs from 'node:fs'
import ts from 'typescript'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const mcpServerRoot = path.resolve(scriptDir, '..')
const repoRoot = path.resolve(mcpServerRoot, '..')
const constantsDir = path.join(repoRoot, 'src', 'constants')
const outDir = path.join(mcpServerRoot, 'src', 'data')

const GENERATED_HEADER = `// AUTO-GENERATED by \`npm run sync\` (scripts/sync-resume-data.ts).
// 원본은 ../../../src/constants 입니다. 이 파일을 직접 수정하지 마세요.
`

function readConstant(fileName: string): string {
  const filePath = path.join(constantsDir, fileName)
  return fs.readFileSync(filePath, 'utf-8')
}

/** `import { X } from '@/types'` 같은 타입 전용 import를 제거한다 (런타임 평가 대상이 아님). */
function stripTypeOnlyImports(source: string): string {
  return source.replace(/^import\s+.*from\s+['"]@\/types['"];?\s*$/gm, '')
}

/** TS/TSX 소스를 CommonJS로 트랜스파일한 뒤 실행하여 export된 값을 얻는다. */
function evalModule(source: string): Record<string, unknown> {
  const { outputText } = ts.transpileModule(stripTypeOnlyImports(source), {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
    },
  })
  const moduleShim = { exports: {} as Record<string, unknown> }
  const fn = new Function('module', 'exports', outputText)
  fn(moduleShim, moduleShim.exports)
  return moduleShim.exports
}

/** skillsets.tsx는 JSX(Icon)를 포함하므로 실행하지 않고 AST에서 name/description만 뽑는다. */
function extractSkillsets(source: string) {
  const sourceFile = ts.createSourceFile('skillsets.tsx', source, ts.ScriptTarget.ES2020, true, ts.ScriptKind.TSX)
  const categoryByVar: Record<string, 'frontend' | 'backend' | 'devOps'> = {
    frontEnds: 'frontend',
    backEnds: 'backend',
    devOps: 'devOps',
  }
  const skills: { name: string; category: 'frontend' | 'backend' | 'devOps'; description: string }[] = []

  function visit(node: ts.Node) {
    if (
      ts.isVariableDeclaration(node) &&
      ts.isIdentifier(node.name) &&
      node.name.text in categoryByVar &&
      node.initializer &&
      ts.isArrayLiteralExpression(node.initializer)
    ) {
      const category = categoryByVar[node.name.text]
      for (const element of node.initializer.elements) {
        if (!ts.isObjectLiteralExpression(element)) continue
        let name = ''
        let description = ''
        for (const prop of element.properties) {
          if (!ts.isPropertyAssignment(prop) || !ts.isIdentifier(prop.name)) continue
          if (prop.name.text === 'name' && ts.isStringLiteral(prop.initializer)) name = prop.initializer.text
          if (prop.name.text === 'description' && ts.isStringLiteral(prop.initializer))
            description = prop.initializer.text
        }
        if (name) skills.push({ name, category, description })
      }
    }
    ts.forEachChild(node, visit)
  }
  visit(sourceFile)
  return skills
}

function writeGenerated(fileName: string, body: string) {
  fs.writeFileSync(path.join(outDir, fileName), GENERATED_HEADER + body, 'utf-8')
  console.log(`  wrote src/data/${fileName}`)
}

function main() {
  console.log(`Syncing resume data from ${path.relative(repoRoot, constantsDir)} ...`)

  const basic = evalModule(readConstant('basic.ts'))
  const summaryModule = evalModule(readConstant('summary.ts'))
  const educationsModule = evalModule(readConstant('educations.ts'))
  const experiencesModule = evalModule(readConstant('experiences.ts'))
  const keySkillsModule = evalModule(readConstant('keySkills.ts'))
  const projectsModule = evalModule(readConstant('projects.ts'))
  const skills = extractSkillsets(readConstant('skillsets.tsx'))

  const profile = {
    name: basic.NAME,
    nameEn: basic.NAME_EN,
    title: basic.TITLE,
    subTitle: basic.SUB_TITLE,
    yearsOfExperience: basic.YEARS_OF_EXPERIENCE,
    email: basic.EMAIL,
    phone: basic.PHONE_NUMBER,
    github: basic.GITHUB_URL,
    behance: basic.BEHANCE_URL,
    address: basic.ADDRESS,
    introduction: summaryModule.INTRODUCTION,
  }

  writeGenerated('profile.ts', `export const PROFILE = ${JSON.stringify(profile, null, 2)} as const\n`)

  writeGenerated(
    'experiences.ts',
    `export interface ProjectDescription {
  title: string
  descriptions: string[]
  information?: string
  url?: string
  impact?: string
  techs?: string[]
}

export interface ExperienceDescription {
  title: string
  details?: string[]
}

export interface Experience {
  name: string
  role?: string
  descriptions: ExperienceDescription[]
  techs: string[]
  joinedAt?: string
  seperatedAt?: string
  isOngoing?: boolean
  url?: string
  projects: ProjectDescription[]
}

export const EXPERIENCES: Experience[] = ${JSON.stringify(experiencesModule.EXPERIENCES, null, 2)}
`,
  )

  writeGenerated(
    'educations.ts',
    `export interface Curriculum {
  title: string
  descriptions: string[]
}

export interface EducationDescription {
  title: string
}

export interface Education {
  name: string
  joinedAt: string
  seperatedAt?: string
  isOngoing?: boolean
  descriptions: EducationDescription[]
  url?: string
  curriculums: Curriculum[]
}

export const EDUCATIONS: Education[] = ${JSON.stringify(educationsModule.EDUCATIONS, null, 2)}
`,
  )

  writeGenerated(
    'skills.ts',
    `export const KEY_SKILLS = ${JSON.stringify(keySkillsModule.KEY_SKILLS, null, 2)} as const

export interface Skill {
  name: string
  category: 'frontend' | 'backend' | 'devOps'
  description: string
}

export const SKILLS: Skill[] = ${JSON.stringify(skills, null, 2)}
`,
  )

  writeGenerated(
    'summaries.ts',
    `export interface Summary {
  title: string
  description: string
  keywords?: string[]
}

export const SUMMARIES: Summary[] = ${JSON.stringify(summaryModule.SUMMARIES, null, 2)}
`,
  )

  writeGenerated(
    'projects.ts',
    `export interface Project {
  title: string
  category: string
  description: string
  url?: string
  techs: string[]
}

export const FEATURED_PROJECTS: Project[] = ${JSON.stringify(projectsModule.FEATURED_PROJECTS, null, 2)}
`,
  )

  console.log('Done.')
}

main()
